<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;

class MessageController extends Controller
{
    public $layout = 'message';

    /**
     * @return array
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}