<?php
/**
 * Created by PhpStorm.
 * User: hovhannes_abovyan
 * Date: 12.12.16
 * Time: 12:09
 */

namespace frontend\widgets;


use yii\base\Widget;

class CategoryTabWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('category-tab');
    }
}