<?php
/**
 * Created by PhpStorm.
 * User: hovhannes_abovyan
 * Date: 12.12.16
 * Time: 12:10
 */

namespace frontend\widgets;


use common\models\Product;
use yii\base\Widget;

class RecommendedItemsWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $hits = Product::find()
            ->where(['hit' => '1'])
            ->limit(6)
            ->all();

        return $this->render('reccommended-items', [
            'hits' => $hits
        ]);
    }
}